/** Flags children easily confuse. Used first as wrong answers when they are in the level's pool. */
export const LOOK_ALIKES: Readonly<Record<string, readonly string[]>> = {
  NL: ['LU', 'FR', 'RU', 'HR', 'PY'],
  LU: ['NL', 'FR', 'RU'],
  FR: ['NL', 'LU', 'RU'],
  RU: ['NL', 'LU', 'FR', 'SK', 'SI', 'RS'],
  SK: ['SI', 'RU'],
  SI: ['SK', 'RU'],
  RS: ['RU'],
  HR: ['NL', 'PY'],
  PY: ['NL', 'HR'],
  IE: ['IT', 'CI'],
  IT: ['IE', 'MX', 'HU'],
  CI: ['IE', 'IT'],
  MX: ['IT'],
  HU: ['IT', 'BG'],
  BG: ['HU'],
  RO: ['TD', 'AD', 'MD'],
  TD: ['RO', 'AD', 'MD'],
  AD: ['RO', 'TD', 'MD'],
  MD: ['RO', 'TD', 'AD'],
  ID: ['MC', 'PL'],
  MC: ['ID', 'PL'],
  PL: ['ID', 'MC'],
  AU: ['NZ'],
  NZ: ['AU'],
  NO: ['IS', 'DK', 'FI', 'SE'],
  IS: ['NO'],
  DK: ['NO', 'SE', 'FI'],
  SE: ['FI', 'DK', 'NO'],
  FI: ['SE', 'DK', 'NO'],
  BE: ['DE'],
  DE: ['BE'],
  SN: ['ML', 'GN'],
  ML: ['SN', 'GN'],
  GN: ['ML', 'SN'],
  VE: ['EC', 'CO'],
  EC: ['CO', 'VE'],
  CO: ['EC', 'VE'],
};
